name: 规则镜像（定时更新）

on:
  workflow_dispatch:     # 允许手动触发
  schedule:
    - cron: '0 */6 * * *'   # 每 6 小时自动运行一次（UTC 时间）

permissions:
  contents: write          # 允许工作流向仓库提交代码

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取当前仓库
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 拉取源规则并生成版本信息
        run: |
          set -e
          mkdir -p data
          # 你先用这两个公共源做演示，后面再按需要增删
          curl -fsSL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.list -o data/Advertising.list
          curl -fsSL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list -o data/Global.list

          python - <<'PY'
          import json, datetime, os
          files = sorted(os.listdir('data'))
          ver = datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S")
          out = {"version": ver, "utc": datetime.datetime.utcnow().isoformat()+"Z", "files": files}
          with open('version.json', 'w', encoding='utf-8') as f:
              json.dump(out, f, ensure_ascii=False, indent=2)
          print(json.dumps(out, ensure_ascii=False, indent=2))
          PY

      - name: 提交并推送更新
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "没有变化，跳过提交"
          else
            git commit -m "chore: 自动更新 $(date -u +'%F %T')"
            git push
          fi
