name: 规则镜像（定时/变更自动更新）

on:
  workflow_dispatch:          # 手动触发
  schedule:
    - cron: '5 6 * * *'       # 每天 06:05 UTC（北京时间 14:05）
  push:
    paths:
      - '.github/workflows/mirror.yml'  # 修改工作流时也跑一次

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.diff.outputs.changed }}
    steps:
      - name: 准备目录
        run: |
          set -e
          rm -rf public
          mkdir -p public/data

      - name: 拉取规则（可用仓库变量覆盖）
        env:
          AD_URL: ${{ vars.AD_URL }}
          GLOBAL_URL: ${{ vars.GLOBAL_URL }}
        run: |
          set -euxo pipefail
          ad_url="${AD_URL:-https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising.list}"
          gl_url="${GLOBAL_URL:-https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global.list}"

          curl -fsSL "$ad_url" -o public/data/Advertising.list || : > public/data/Advertising.list
          curl -fsSL "$gl_url" -o public/data/Global.list      || : > public/data/Global.list

          printf '{"version":"%s"}\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > public/version.json

      - name: 获取线上已发布版本用于对比（若首次部署则忽略）
        id: pull
        continue-on-error: true
        run: |
          set -eux
          mkdir -p old
          # 线上 Pages URL： https://<owner>.github.io/<repo>/
          curl -fsSL "https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/data/Advertising.list" -o old/Advertising.list
          curl -fsSL "https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/data/Global.list"      -o old/Global.list

      - name: 对比是否有变化
        id: diff
        shell: bash
        run: |
          set -e
          changed=false
          for f in Advertising.list Global.list; do
            if [[ -f "old/$f" ]] && cmp -s "old/$f" "public/data/$f"; then
              echo "NO change in $f"
            else
              echo "Change found in $f"
              changed=true
            fi
          done
          echo "changed=$changed" >> "$GITHUB_OUTPUT"

      - name: 生成中文首页
        shell: bash
        run: |
          cat > public/index.html <<'HTML'
          <!doctype html>
          <html lang="zh-CN">
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <title>规则镜像</title>
          <style>
            body{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,"PingFang SC","Microsoft YaHei",sans-serif;max-width:920px;margin:36px auto;padding:0 20px;line-height:1.6}
            h1{font-size:24px;margin:0 0 16px}
            ul{padding-left:18px;margin:18px 0}
            a{color:#0969da;text-decoration:none} a:hover{text-decoration:underline}
            .muted{color:#6e7781;font-size:14px}
          </style>
          <h1>规则镜像</h1>
          <ul>
            <li><a href="data/Advertising.list">广告规则（Advertising.list）</a></li>
            <li><a href="data/Global.list">全球规则（Global.list）</a></li>
            <li><a href="version.json">版本信息（version.json）</a></li>
          </ul>
          <p id="ts" class="muted">更新时间：加载中…</p>
          <script>
            fetch('version.json').then(r=>r.json()).then(j=>{
              document.getElementById('ts').textContent='更新时间：'+j.version;
            }).catch(()=>{});
          </script>
          </html>
          HTML

      - name: 配置 Pages
        uses: actions/configure-pages@v5

      - name: 无变化则跳过上传
        if: steps.diff.outputs.changed == 'false'
        run: echo "No change, skip upload."

      - name: 上传构建产物
        if: steps.diff.outputs.changed == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    if: needs.build.outputs.changed == 'true'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 发布到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
