      - name: 生成中文首页
        if: steps.diff.outputs.changed == 'true'
        shell: bash
        run: |
          cat > public/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <title>规则镜像</title>
          <style>
          body{font-family:system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,"PingFang SC","Microsoft YaHei",sans-serif;max-width:820px;margin:28px auto;padding:0 12px;line-height:1.6}
          h1{font-size:22px;margin:0 0 12px}
          ul{padding-left:18px;margin:12px 0}
          a{color:#0969da;text-decoration:none}
          a:hover{text-decoration:underline}
          .muted{color:#6e7781;font-size:14px}
          </style>

          <h1>规则镜像</h1>
          <ul>
            <li><a href="data/Advertising.list">广告规则（Advertising.list）</a></li>
            <li><a href="data/Global.list">全球规则（Global.list）</a></li>
            <li><a href="version.json">版本记录（version.json）</a></li>
          </ul>
          <p class="muted">更新时间：<span id="ts">加载中…</span></p>

          <script>
            fetch('version.json').then(r=>r.json()).then(j=>{
              document.getElementById('ts').textContent = j.version;
            }).catch(()=>{});
          </script>
          HTML
