name: Mirror rules to Pages（同步规则到 Pages）
on:
  workflow_dispatch: {}                 # 手动运行（Run workflow）
  schedule:
    - cron: "*/10 * * * *"             # 可选：每 10 分钟同步一次

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rules-mirror（检出镜像仓）
        uses: actions/checkout@v4

      - name: Fetch latest rule（拉取最新规则）
        run: |
          mkdir -p payroll
          curl -fsSLo payroll/active.md \
            "https://raw.githubusercontent.com/jj5638521/huijiang-assistant/main/rules/01_工资模块_latest.md?plain=1"
          test -s payroll/active.md       # 非空断言，避免发布空文件
          touch .nojekyll                 # 禁用 Jekyll

      - name: Commit if changed（有变更才提交）
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add payroll/active.md .nojekyll
          if ! git diff --cached --quiet; then
            git commit -m "Mirror: update active.md"
            git push
          else
            echo "No change."
          fi
